pipeline {
    agent {
        node {
            label 'master'
 
             
    }
    }
    
   
      
    stages {
   
    /*    stage ("test"){
            steps {
                     def installed = fileExists 'bin/activate'
             
             if (!installed) {
                 stage("Install Python Virtual Enviroment") {
                 echo 'Virtual env not found'       
        }
     }
            }
        }   
   */
        
     stage ("Install Application Dependencies") {
         steps {
            sh '''
            source testvir/project/bin/activate
//            pip install -r <relative path to requirements file>
            deactivate
           '''
         }
    }
    
    
     stage ("Collect Static files") {
         steps {
            sh '''
            source testvir/project/bin/activate
            python3 manage.py collectstatic --noinput
            deactivate
           '''
         }    }
    }
    }
